### PR TITLE
Merge pull request #1 from caiomsouza/master

### PR DESCRIPTION
**Pull request by joaopauloramos**
Permitir que faça update do Fork

### CODE REVIEW

**Comment by joaopauloramos** [comment]
Update

**Comment by joaopauloramos** [comment]
Updated

**Comment by joaopauloramos** [comment]
updated

**Comment by joaopauloramos** [comment]
updated

**Comment by joaopauloramos** [comment]
updated

**Comment by caiomsouza** [comment]
Feito.

**Pull request merged**
